export const FETCH_ARTICLES       = 'FETCH_ARTICLES';
export const ARTICLES_RECEIVED    = 'ARTICLES_RECEIVED';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_ARTICLE    = 'FETCH_ARTICLE';
export const ARTICLE_RECEIVED = 'ARTICLE_RECEIVED';

export const ARTICLE_PREVIEW_RECEIVED = 'ARTICLE_PREVIEW_RECEIVED';
export const ARTICLE_PREVIEW_FAILED = 'ARTICLE_PREVIEW_FAILED';
