FROM nginx:alpine

ENV APP_HOME /usr/src/app/

RUN mkdir $APP_HOME


WORKDIR $APP_HOME
RUN rm -rf /etc/nginx/sites-available/default
ADD config/stupid_code_factory_blog.conf /etc/nginx/sites-enabled/nginx.conf

EXPOSE 80
EXPOSE 443
ADD ./public $APP_HOME
CMD [ "nginx", "-g", "daemon off;" ]
