FROM nginx:alpine

COPY public /usr/share/nginx/html

RUN rm -rf /etc/nginx/sites-available/default
ADD config/stupid_code_factory_blog.conf /etc/nginx/sites-enabled/nginx.conf

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]
