version: "3"
services:
  postgres:
    image: postgres:9-alpine
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: bin/rails s -b 0.0.0.0
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"
      - "3035:3035"
