FROM nginx:alpine

RUN rm -rf /etc/nginx/sites-available/default /usr/share/nginx/html/*

COPY public /usr/share/nginx/html/

ADD config/stupid_code_factory_blog.conf /etc/nginx/conf.d/

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]
