FROM node

ENV APP_HOME /usr/src/app/

RUN mkdir $APP_HOME

RUN npm install -g yarn

ADD ./yarn* $APP_HOME
ADD ./package.json $APP_HOME
ADD ./.babelrc $APP_HOME

WORKDIR $APP_HOME
RUN yarn install

CMD ["yarn", "exec"]
