version: 2
jobs:
  deploy:
    working_directory: ~/stupid_code_factory_blog
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
      # - restore_cache:
      #     key: pip-{{ checksum "requirements.txt" }}
      - run: pip install --upgrade --user -r requirements.txt
      - run:
          name: configure aws
          command:
            aws configure set default.region eu-west-1
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - setup_remote_docker:
          reusable: true
      - deploy:
          name: Push application Docker image
          command: |
            export PATH="$PATH:~/.local/bin"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              $(aws ecr get-login --no-include-email --region eu-west-2)
              ECR_ENDPOINT=466565482925.dkr.ecr.eu-west-2.amazonaws.com
              docker build -t  "stupid-code-factory-blog:${CIRCLE_SHA1}" .
              docker tag  "stupid-code-factory-blog:${CIRCLE_SHA1}" "${ECR_ENDPOINT}/stupid-code-factory-blog:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/stupid-code-factory-blog:${CIRCLE_SHA1}"
            fi
  build:
    working_directory: ~/stupid_code_factory_blog
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:alpine
      - image: elasticsearch
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          key: rails-{{ checksum "Gemfile.lock" }}



      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Set up db
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
