version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/stupid_code_factory_blog
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:alpine
      - image: elasticsearch
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: rails-{{ checksum "Gemfile.lock" }}

      - setup_remote_docker

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: sudo apt-get install python
      - run: python --version
      - run: pip install awscli --upgrade --user
      # Store bundle cache
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Set up db
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - run: |
          TAG=$CIRCLE_BRANCH-latest
          docker build -t stupid-code-factory-blog .
          docker tag stupid-code-factory-blog:$TAG 466565482925.dkr.ecr.eu-west-2.amazonaws.com/stupid-code-factory-blog:$TAG
          $(aws ecr get-login --no-include-email --region eu-west-2)
          docker push 466565482925.dkr.ecr.eu-west-2.amazonaws.com/stupid-code-factory-blog:$TAG
