# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26dfdc34d72f42d7061f37d9218870d6916c31d827699f998661726cf79edf1a0c117489bf024bb0b42edb4e4a45584ab79c76af1386e0bccab67a86b8a71530

test:
  secret_key_base: 021f47f4803111ae0ded63c433015d58fb1d8cfcd4cc94233df0f994b2e9f8429867b01b62ec99e9d0d669051597599bda421b92783c6700d1a384248ea81a41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
